[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "large_contract"

[dependencies]
large_contract_interface = { path = "../large_contract_interface" }
