[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "large_contract"

[proxy]
enabled = true
address = "0x4f8300559cd511ddc411e8180036f0b56fb348b76ed49b0948917faaee167cb7"
